# Generated by Django 3.1.4 on 2024-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20240209_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='working',
        ),
    ]
