# Generated by Django 3.1.4 on 2024-02-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20240209_1845'),
        ('Employee', '0003_remove_employee_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
