# Generated by Django 3.1.4 on 2024-02-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20240209_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
