# Generated by Django 3.1.4 on 2024-02-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20240209_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_id',
        ),
    ]
