# Generated by Django 3.1.4 on 2024-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20240209_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
