# Generated by Django 3.1.4 on 2024-02-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_remove_employee_task_id'),
        ('tasks', '0003_auto_20240209_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.CreateModel(
            name='works_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
